[project]
name = "call-me-maybe"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "numpy",
    "pydantic>=2,<3",
]

[tool.uv]
package = false
constraint-dependencies = [
    "transformers>=4.51,<5",
    "torch>=2.6",
]

[tool.uv.sources]
llm-sdk = { path = "./llm_sdk" }