[project]
name = "call-me-maybe"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "numpy",
    "pydantic>=2,<3",
]

[tool.uv]
package = false
constraint-dependencies = [
    "transformers>=4.51,<5",
    "torch>=2.6",
]

[tool.uv.sources]
llm-sdk = { path = "./llm_sdk" }

[dependency-groups]
dev = [
    "flake8>=7.4.1",
    "mypy>=2.3.1",
]

[tool.mypy]
python_version = "3.10"
mypy_path = ["$MYPY_CONFIG_FILE_DIR/llm_sdk"]
show_error_codes = true
pretty = true
exclude = [
    "(^|/)\\.venv/",
    "(^|/)myenv/",
    "(^|/)\\.mypy_cache/",
    "(^|/)\\.pytest_cache/",
    "(^|/)__pycache__/",
    '^llm_sdk/',
]

[[tool.mypy.overrides]]
module = "llm_sdk"
disable_error_code = ["arg-type"]